"""Build Hyperagent — concatenates CSS and emits per-module JS <script> blocks
into the inline HTML shell.

WI-118: Each JS module is emitted as its own <script> block so that a parse
error in one module does not abort the entire bundle. Top-level `let`/`const`
declarations in classic scripts share a common global lexical environment,
so cross-module references (e.g. shared `state`, `msgs`, `input`) keep working
without any explicit `window.` prefix.

Usage: python build.py
Output: Updates the HTML variable in generated_html.py
"""
import glob
from pathlib import Path

ROOT = Path(__file__).parent


def concat_files(pattern):
    files = sorted(glob.glob(str(ROOT / pattern)))
    return "\n".join(Path(f).read_text(encoding="utf-8") for f in files)


def render_js_blocks():
    """Emit one <script> block per JS module, preserving concat order.

    Each block is its own execution context — a SyntaxError in one module
    only kills that block; subsequent modules still parse and execute.
    """
    files = sorted(glob.glob(str(ROOT / "assets/js/*.js")))
    blocks = []
    for f in files:
        content = Path(f).read_text(encoding="utf-8")
        name = Path(f).name
        blocks.append(f"<!-- {name} -->\n<script>\n{content}\n</script>")
    return "\n".join(blocks)


def build():
    css = concat_files("assets/css/*.css")
    js_blocks = render_js_blocks()
    shell = (ROOT / "assets/shell.html").read_text(encoding="utf-8")
    html = shell.replace("{{CSS}}", css).replace("{{JS_BLOCKS}}", js_blocks)

    # Write as a Python module using repr() to safely escape all characters
    out = ROOT / "generated_html.py"
    out.write_text(
        f'"""Auto-generated by build.py — do not edit."""\n\nHTML = {repr(html)}\n',
        encoding="utf-8"
    )
    js_total = sum(
        len(Path(f).read_text(encoding="utf-8"))
        for f in sorted(glob.glob(str(ROOT / "assets/js/*.js")))
    )
    js_count = len(sorted(glob.glob(str(ROOT / "assets/js/*.js"))))
    print(f"Built: {len(css)} bytes CSS, {js_total} bytes JS across {js_count} modules -> generated_html.py")


if __name__ == "__main__":
    build()
