"""Build Hyperagent — concatenates CSS and JS into the inline HTML shell.

Usage: python build.py
Output: Updates the HTML variable in hyperagent.py
"""
import glob
from pathlib import Path

ROOT = Path(__file__).parent

def concat_files(pattern):
    files = sorted(glob.glob(str(ROOT / pattern)))
    return "\n".join(Path(f).read_text(encoding="utf-8") for f in files)

def build():
    css = concat_files("assets/css/*.css")
    js = concat_files("assets/js/*.js")
    shell = (ROOT / "assets/shell.html").read_text(encoding="utf-8")
    html = shell.replace("{{CSS}}", css).replace("{{JS}}", js)

    # Write as a Python module using repr() to safely escape all characters
    out = ROOT / "generated_html.py"
    out.write_text(
        f'"""Auto-generated by build.py — do not edit."""\n\nHTML = {repr(html)}\n',
        encoding="utf-8"
    )
    print(f"Built: {len(css)} bytes CSS, {len(js)} bytes JS -> generated_html.py")

if __name__ == "__main__":
    build()
